language: elm
before_install:
  - npm install -g uglify-js
jobs:
  include:
    - stage: test
      script: 
        - elm-format --validate .
        - echo "$TRAVIS_COMMIT_RANGE"
        - CHANGED_FILES="$(git diff --name-only $TRAVIS_COMMIT_RANGE)"
        - echo "$CHANGED_FILES"
      name: "Elm Format Validation"
    - script: elm-test
      name: "Elm-Test Test Run"
    - stage: deploy
      script: echo "Hello World!"
stages:
  - test
  - name: deploy
    if: (branch = master) AND (type = push)