language: elm
before_install:
  - npm install -g uglify-js
jobs:
  include:
    - stage: test-format
      script: elm-format --validate .
    - stage: test
      script: elm-test
stages:
  - test
  - test-format
