language: elm
before_install:
  - npm install -g uglify-js
jobs:
  include:
    - stage: test
      name: "Elm Format Validation"
      script: elm-format --validate .
      name: "Elm-Test Test Run"
      script: elm-test
stages:
  - test
